### ISSUE TITLE
Rid of sleep in specs

### ISSUE THREAD

**Issue by Tonkpils** [Tonkpils/celluloid-eventsource#10]
Find a better way to test that events are received without using sleep

**Comment by nandosola** [comment]
I'm actually making good progress on this. There were a couple of problems:

1) Using Reel as a dummy SSE server is IMO quite hardcore. I'm developing a lighter alternative based on WebRick and plain threads. Celluloid actors don't like to be terminated immediately, so they hang around and mess with the next test. The server is started by a memoized RSpec runner:

```ruby
module ServerRunner
  def run_server(name, &block)
    let! name do
      server = block.call
      Thread.new{server.start}
      trap 'INT' do server.shutdown end
      server
    end

    after do
      send(name).shutdown
    end
  end
end

RSpec.configure { |c| c.extend ServerRunner }

```
This idea was actually stolen from [http.rb](https://github.com/httprb/http.rb/tree/master/spec/support).

2) Testing callbacks is simpler if futures are used:

```ruby
run_server(:dummy) { DummyServer.new }
let(:future) { Celluloid::Future.new }
let(:value_class) { Class.new(Struct.new(:value)) }
let(:data) { "foo bar " }

describe '#on_open' do

  it 'the client has an opened connection' do

    Celluloid::EventSource.new("http://localhost:63310") do |conn|
      conn.on_open do
        future.signal(value_class.new({ called: true, state: conn.ready_state }))
        conn.close
      end
    end

    expect(future.value).to eq({ called: true, state: Celluloid::EventSource::OPEN })
  end
```

So, this is where I'm headed to. Please let me know what you think. 

Cheers!
//n

**Comment by Tonkpils** [comment]
@nandosola I like the idea of using a lighter sse dummy server and using futures instead of `sleep`. I believe `#value` also takes in a timeout argument which would definitely be much better than sleeping to wait for a value. Can't wait to see the result of this :+1:
